DELETE FROM script;

INSERT INTO script(id, name, language, description, category_id, body, variables, version, date_created, last_updated) VALUES ('descuento-edad', 'Descuento por edad', 'groovy', 'Descuento a personas por su edad', 'promocion', 'if(moment == ''beforeTotal'') { def typeMap = [ "Infante": "infant", "Niño": "child", "Adulto": "adult", "Adulto mayor": "senior" ]; def personType = typeMap[variables.personType]; def normalizedPercentage = 1 - (variables.percentage / 100); quote.tickets.grep { it.personType == personType }.each { it.calculatedPrice = it.basePrice * normalizedPercentage; } ; if(variables.percentage < 100) { quote.promoMessages.add(''Los '' + variables.personType.toLowerCase() + ''s tienen '' + variables.percentage + ''% de descuento'') } else { quote.promoMessages.add(''Los '' + variables.personType.toLowerCase() + ''s no pagan'') };  }', '{ "type": "object", "title": "Script Variables", "properties": { "percentage": { "title": "Porcentaje", "type": "number" }, "personType": { "title": "Tipo de persona", "type": "string", "enum": [ "Infante", "Niño", "Adulto", "Adulto mayor" ] } }, "required": [ "percentage" ] }', 0, current_timestamp, current_timestamp);

INSERT INTO script(id, name, language, description, category_id, body, variables, version, date_created, last_updated) VALUES ('compra-mayor', 'Compra mayor a x', 'groovy', 'Descuento a compras mayores a un valor tienen un descuento de un porcentaje', 'promocion', 'if(moment == ''afterTotal'' && quote.totalPrice > variables.minValue) { quote.totalPrice = quote.totalPrice * (1 - variables.percentage / 100); quote.promoMessages.add(''Descuento del '' + variables.percentage + ''% en compras mayores a $'' + variables.minValue); }', '{ "type": "object", "title": "Script Variables", "properties": { "minValue": { "title": "Valor mínimo", "type": "number" }, "percentage": { "title": "Porcentaje", "type": "number" } }, "required": [ "minValue", "percentage" ] }', 0, current_timestamp, current_timestamp);


INSERT INTO promotion(id, name, variables, script_id, version, date_created, last_updated) VALUES('children-promotion', 'Los niños pagan menos', ' { "percentage": 20.0, "personType": "Niño" } ', 'descuento-edad', 0, current_timestamp, current_timestamp);
INSERT INTO promotion(id, name, variables, script_id, version, date_created, last_updated) VALUES('infants-promotion', 'Infantes no pagan', ' { "percentage": 100.0, "personType": "Infante" } ', 'descuento-edad', 0, current_timestamp, current_timestamp);
INSERT INTO promotion(id, name, variables, script_id, version, date_created, last_updated) VALUES('test-promotion', '10% de descuento si compras mas de $500', ' { "percentage": 10.0, "minValue": 500.0 } ', 'compra-mayor', 0, current_timestamp, current_timestamp);
