ALTER TABLE sale_item ADD COLUMN name VARCHAR(256) NULL;
ALTER TABLE sale_item ADD COLUMN first_last_name VARCHAR(256) NULL;
ALTER TABLE sale_item ADD COLUMN second_last_name VARCHAR(256) NULL;
ALTER TABLE sale_item ADD COLUMN person_type VARCHAR(256) NULL;
